FRAUD_THRESHOLD = 0.75
MAX_LATENCY_MS = 500
ML_SCORING_TIMEOUT_MS = 200
GRAPH_ANALYSIS_TIMEOUT_MS = 150

REDIS_HOST = "localhost"
REDIS_PORT = 6379
REDIS_TTL = 3600

GRAPH_WINDOW_HOURS = 24
MIN_FRAUD_RING_SIZE = 3
MAX_TRANSACTION_VELOCITY = 10

BIOMETRIC_WEIGHT = 0.2
ML_SCORE_WEIGHT = 0.5
GRAPH_SCORE_WEIGHT = 0.3
